name: Validate Merge

on:
  pull_request:
    branches: [master]

jobs:
  validate-merge:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.2

    - name: Install GoGen Avro
      run: |
        go install github.com/actgardner/gogen-avro/v10/cmd/...@latest

    - name: Checkout Merged Branch
      uses: actions/checkout@v2

    - name: Gen Code
      run: |
        make avro

    - name: Validate
      run: |
        ./validate.sh --nofmt --cov --race 10
      env:
        GO111MODULE: "on"
